name: Image Build and Push

on:
  push:
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: DockerHubProd
    steps:
      # For building the image we need to checkout the source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Docker Buildx for multiplatform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Preparing tag name
      - name: Prepare tag name
        id: prepare_tag
        run: |
          git_tag_name=${{ github.ref_name }};
          echo Verifying that the tag name matches the expected format...
          if [[ ! "$git_tag_name" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: Tag name '$git_tag_name' does not match the expected format 'vX.Y.Z'.";
            exit 1;
          else
            echo "Tag name '$git_tag_name' is valid.";
          fi;
          echo Cleaning the tag name from the first v character...
          docker_image_tag_name=${git_tag_name:1};
          echo "docker_image_tag_name: $docker_image_tag_name";
          echo "docker_image_tag_name=$docker_image_tag_name" >> $GITHUB_ENV;

      # Build and push multiplatform Docker image
      - name: Build multiplatform Docker image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: |
            ${{ vars.DOCKER_ORG }}/spfx:${{ env.docker_image_tag_name }}
            ${{ vars.DOCKER_ORG }}/spfx:latest
            ${{ vars.DOCKER_ORG }}/spfx:online
          target: default
